services:
  picopark-app:
    image: dylanaragon/picopark:latest
    container_name: picopark-prod
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - picopark-network

  gamepad-app:
    build:
      context: ./GamePad
      dockerfile: Dockerfile
    container_name: gamepad-prod
    ports:
      - "3002:3000"
    restart: unless-stopped
    networks:
      - picopark-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - picopark-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - picopark-network

networks:
  picopark-network:
    driver: bridge
